### ISSUE TITLE
reenable git-annex?

### ISSUE THREAD

**Issue by etam** [opensuse-haskell/configuration#24] opened 2018-11-22 15:01 UTC
I see that in #15 git-annex was dropped. But can it be enabled again? It's source repo shows some activity, and in `stack.yaml` it has `lts-12.19`.

**Comment by peti** [comment] 2018-11-22 20:16
The problem supporting `git-annex` is not so much `git-annex` itself. Joey Hess is very active and quite responsive to questions and support requests. The problems are caused by `git-annex`'s dependencies, some of which are outdated and unmaintained and no longer work in a recent version of the Haskell ecosystem.

I can give it another try, but in the past `git-annex` support has been quite painful, really, and I'm not super enthusiastic about going through all that again.

**Comment by peti** [comment] 2018-11-23 14:12
We still cannot build `git-annex` I'm afraid:

~~~
$ cabal v1-install --dry-run "git-annex >7"
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: git-annex-7.20181105 (user goal)
[__1] trying: esqueleto-2.5.3 (dependency of git-annex)
[__2] next goal: base (dependency of git-annex)
[__2] rejecting: base-4.12.0.0/installed-4.1... (conflict: esqueleto =>
base>=4.8 && <4.11)
[__2] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, esqueleto, git-annex)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, git-annex, esqueleto
~~~

The dependency `esqueleto` needs an update before can use it.

**Closed by peti** 2018-11-23 14:12 UTC

**Comment by etam** [comment] 2018-11-23 15:04
Just for reference: https://github.com/bitemyapp/esqueleto/issues/105

**Comment by peti** [comment] 2018-12-04 12:38
Recent versions of `git-annex` have dropped the dependency on `esqueleto`. That might open some doors for us.
